<?php

// }
/*HOOKS*/
/**TODO
-request RSS feed for homepage and cross reference positional information in feed with recent articles to pull out important stories and keep them near the top.
-lets keep track of which articles have the most views on the site by adding a counter to each article and incrementing it through the endpoint. Probably best to increment these by nid
-Add a headless return for all article pages if user is not type administrator.

*/
/**
 * Implements hook menu
 * Provides two json endpoints :D
 */
// function mytimes_core_menu() {
//   $items['set/%'] = array(
//     'page callback' => 'rheo_core_set_data',
//     'page arguments' => array(1),
//     'access arguments' => array('access content')
//   );
//   return $items;
// }

// function mytimes_core_set_data($request) {
//   $name = "Access-Control-Allow-Origin";
//   $value = "http://rheomail.com";
//   drupal_add_http_header($name, $value, $append = TRUE);
//   // $client_ip = $_SERVER['REMOTE_ADDR'];
//   // dpm($client_ip);
//   //no switch statement
//   dpm($_POST);
// }


function mytimes_core_cronapi($op,$job = NULL) {
  $items['mytimes_core_update_articles'] = array(
      'description' => 'Cron job to update articles on the site every minute',
      'rule' => '* * * * *',//change me to all asterisks later
      'callback' => 'mytimes_core_create_articles',
      'arguments' => array('0')//this is unnecessary, but whatever
    );
  return $items;
}

function mytimes_core_prepare_article_data($wrapper) {
  if($wrapper->type->value() == "article") {
    //map the values
    $nid = $wrapper->nid->value();
    $path = $wrapper->field_source_url->value();
    $title = $wrapper->title->value();
    $author = $wrapper->field_author->value();
    $body = $wrapper->body->value()['value'];
    $date = $wrapper->field_date_published->value();
    $thumb = $wrapper->field_thumbnail_path->value();
    $normal = $wrapper->field_large_path->value();
    $large = $wrapper->field_jumbo_path->value();
    $section = $wrapper->field_section->value();
    $subsection = $wrapper->field_subsection->value();
    $image = array();
    if($thumb) {
      $image['thumb'] = $thumb;
      $image['normal'] = $normal;
      $image['large'] = $large;
    }
    $section_render = NULL;
    $subsection_render = NULL;
    if($section) {
      $section_render = mytimes_core_render_taxonomy($section);
    }
    if($subsection) {
      $subsection_render = mytimes_core_render_taxonomy($subsection);
    }

    //form a result object
    $result = array(
      'nid' => $nid,
      'title' => $title,
      'path' => $path,
      'author' => $author,
      'body' => $body,
      'date' => $date,
      'image' => $image,
      'section' => array(
        'rendered' =>$section_render,
        'details' => $section
      ),
      'subsection' => array(
        'rendered' => $subsection_render,
        'details' => $subsection
      )
    );
  } else {
    //there is no result.
    $result = FALSE;
  }
  return $result;
}

function mytimes_core_render_taxonomy($term_obj) {
  $tid = $term_obj->tid;
  $calc_path = "taxonomy/term/" . $tid;
  $path = drupal_lookup_path('alias', $calc_path);
  $name = $term_obj->name;

  $output = "<a href='/" . $path . "'>" . $name . "</a>";
  return $output;
}

function mytimes_core_create_articles($argument) {
  //get article data
  $url = "http://api.nytimes.com/svc/news/v3/content/nyt/all?";
  $api_string = "api-key=070cd311de7c5d235e85830bae85cb22:14:56579220";
  $request_path = $url . $api_string;
  $returned_json = file_get_contents($request_path);
  $results = drupal_json_decode($returned_json);
  // dpm($results);

  $oldestFirst = array_reverse($results['results']);
  //loop over the results
  foreach($oldestFirst as $result) {
    //make sure these are zeroed out at the beginning of each loop.
    $superJumbo = NULL;
    $basicLarge = NULL;
    $thumbLarge = NULL;
    $multimedia = $result['multimedia'];
    //set up images, if the article has them.
    //process date object
    $dateObj = new DateTime(date($result['updated_date']));
    $title = $result['title'];
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type','node')
        ->entityCondition('bundle','article')
        ->propertyCondition('title',$title);
        // ->fieldCondition('field_date_published','value',$dateObj->getTimestamp(),'=');
    $query_result = $query->execute();
    if(empty($query_result)) {
      //go for it.
      if(!empty($multimedia)) {
        $image_path = $multimedia[0]['url'];
        $components = explode("/",$image_path);
        $length = count($components);
        $index = $length - 2;
        $base_name = $components[$index];
        $calc_path = "http://";
        for($i = 2; $i < count($components) - 1; $i++) {
          $calc_path .= $components[$i] . "/";
        }
        $superJumbo = $calc_path . $base_name . "-superJumbo.jpg";
        $basicLarge = $calc_path . $base_name . "-sfSpan.jpg";
        $thumbLarge = $calc_path . $base_name . "-thumbLarge.jpg";
      }
      $values = array(
        'type' => 'article',
        'uid' => 1,
        'status' => 1,
        'comment' => 0,
        'promote' => 0,
      );
      $entity = entity_create('node', $values);
      $wrapper = entity_metadata_wrapper('node', $entity);
      //preprocess tids
      $section_tid = mytimes_core_get_term('section',$result['section']);
      $subsection_tid = mytimes_core_get_term('subsection',$result['subsection']);
      $des_tids = mytimes_core_get_term('des_facet',$result['des_facet']);
      $org_tids = mytimes_core_get_term('org_facet',$result['org_facet']);
      $per_tids = mytimes_core_get_term('per_facet',$result['per_facet']);
      $geo_tids = mytimes_core_get_term('geo_facet',$result['geo_facet']);
      if(isset($result['blog_name'])) {
        $blog_tid = mytimes_core_get_term('blog_name',$result['blog_name']);
        $wrapper->field_blog_name->set($blog_tid);
      }
      $item_tid = mytimes_core_get_term('item_type',$result['item_type']);
      $material_tid = mytimes_core_get_term('material_type_facet',$result['material_type_facet']);
      
      //set values on the wrapper
      $wrapper->field_section->set($section_tid);
      $wrapper->field_subsection->set($subsection_tid);
      $wrapper->title->set($result['title']);
      $wrapper->body->set(array('value' => $result['abstract']));
      $wrapper->field_author->set($result['byline']);
      $wrapper->field_source_url->set($result['url']);
      $wrapper->field_subheadline->set($result['subheadline']);
      $wrapper->field_item_type->set($item_tid);
      $wrapper->field_material_type_facet->set($material_tid);
      $wrapper->field_kicker->set($result['kicker']);
      $wrapper->field_des_facet->set($des_tids);
      $wrapper->field_org_facet->set($org_tids);
      $wrapper->field_per_facet->set($per_tids);
      $wrapper->field_geo_facet->set($geo_tids);
      $wrapper->field_date_published->set($dateObj->getTimestamp());
      if(isset($superJumbo)) {
        $wrapper->field_thumbnail_path->set($thumbLarge);
        $wrapper->field_jumbo_path->set($superJumbo);
        $wrapper->field_large_path->set($basicLarge);
        //we have an image
      } else {
        //we don't :(
        //no other actions now.
      }
      $wrapper->save();

      //take care of socket data.
      //since we're going backwards through the items, we should encounter older stuff first (we hope)
      $socket_update = mytimes_core_prepare_article_data($wrapper);
      $socket_subject = "new_post";
      $socket_update = drupal_json_encode($socket_update);
      nodejs_broadcast_message($socket_subject,$socket_update);
    } else {
      //don't do anything.
    }
  }
  //end of loop
  //create the nodes
}

//this function is pretty good.
//returns tid(s) for requested term name(s) in a vocabulary set
function mytimes_core_get_term($vocabulary,$term_name) {
  if($term_name != "") {
    if(!is_array($term_name)) {
      return mytimes_core_get_single_term($vocabulary,$term_name);
    } else {
      $tids = array();
      foreach($term_name as $term) {
        $tids[] = mytimes_core_get_single_term($vocabulary,$term);
      }
      return $tids;
    }
  } else {
    return NULL;
  }
}

//function to get term tids if they exist, or create them if they do not.
function mytimes_core_get_single_term($vocabulary,$term_name) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type','taxonomy_term')
        ->entityCondition('bundle',$vocabulary)
        ->propertyCondition('name', $term_name);
  $result = $query->execute();
  if(empty($result)) {
    //create the term.
    $vid = taxonomy_vocabulary_machine_name_load($vocabulary)->vid;
    $term = new stdClass();
    $term->name = $term_name;
    $term->vid = $vid;
    taxonomy_term_save($term);
    return $term->tid;
  } else {
    foreach($result['taxonomy_term'] as $key=>$term_obj) {
      return $key; //we avoid looping through everything by returning the first tid we found.
    }
  }
}

